### update request to example server
PUT http://localhost:4000/patients/223e4567-e89b-12d3-a456-426614174005
Content-Type: application/json

{
  "name": "thanveer-1",
  "email": "test_update@example.com",
  "address": "123 main street",
  "dateOfBirth": "1992-09-11"
}
###